### ISSUE TITLE
item is undefined when managing databases

### ISSUE THREAD

**Issue by jtl999** [mrlesmithjr/ansible-mysql#17]
Full error with redacted path

```
fatal: [alpine-dns]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/jtl/<snip>/ansible-mysql/tasks/dbs.yml': line 2, column 3,
```

My playbook looks like this

```
---
- hosts: alpine-dns
  roles:
      - ansible-mysql
  vars:
      mysql_dbs:
          name: pdns
          state: present
      mysql_root_password: changme
      mysql_db_users:
          - name: pdns
            password: changeme
            state: present
            privs:
                - db: pdns
                  host: 127.0.0.1
                  table: "*"
                  priv: ALL
```
